version: "3"
services:
  gpsutil:
    container_name: gpsutil
    image: gpsutil:latest
    ports:
      - "8081:8080"

  reward-central:
    container_name: rewardCentral
    image: rewardcentral:latest
    ports:
      - "8082:8080"

  trip-pricer:
    container_name: tripPricer
    image: trippricer:latest
    ports:
      - "8083:8080"

  tour-guide:
    container_name: tourGuide
    build: .
    ports:
      - "8080:8080"


