version: "3"
services:
  gpsutil:
    image: gpsutil:latest
    ports:
      - "8081:8080"

  reward-central:
    image: rewardcentral:latest
    ports:
      - "8082:8080"

  trip-pricer:
    image: trippricer:latest
    ports:
      - "8083:8080"


